version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    driver: bridge