version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    expose:
      - "5100"
    environment:
      - FLASK_ENV=development


  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge